import {
  User,
  InvestigationCase,
  Entity,
  EntityResolutionCandidate,
  Relationship,
  Evidence,
  TimelineEvent,
  MapLocation,
  AIFinding,
  IntelligenceReport,
  AuditLog,
} from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Inspector Rajesh Varma',
    email: 'rajesh.varma@crimeintel.gov.in',
    role: 'INVESTIGATOR',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    department: 'Special Crime Branch & Cyber Cell',
    badgeNumber: 'SCB-8849',
  },
  {
    id: 'usr-2',
    name: 'Dr. Priya Sundaram',
    email: 'priya.sundaram@crimeintel.gov.in',
    role: 'ANALYST',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    department: 'Criminal Network Intelligence Unit',
    badgeNumber: 'CNIU-2210',
  },
  {
    id: 'usr-3',
    name: 'Superintendent K. S. Rao',
    email: 'ks.rao@crimeintel.gov.in',
    role: 'SUPERVISOR',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    department: 'Directorate of Intelligence Services',
    badgeNumber: 'DIS-0012',
  },
  {
    id: 'usr-4',
    name: 'System Administrator',
    email: 'admin@crimeintel.gov.in',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    department: 'IT Security & Audit Command',
    badgeNumber: 'ADMIN-0001',
  },
];

export const MOCK_CASES: InvestigationCase[] = [
  {
    id: 'case-101',
    caseNumber: 'CASE-2026-8812',
    title: 'Operation Shadow Vault: Cyber Financial Syndicate',
    description: 'Investigation into an organized cross-border phishing, mule account network, and cryptocurrency money laundering operation involving shell companies.',
    status: 'UNDER_INVESTIGATION',
    priority: 'CRITICAL',
    crimeType: 'Cyber Crime & Financial Fraud',
    assignedTo: 'usr-1',
    assignedUserName: 'Inspector Rajesh Varma',
    locationName: 'Bengaluru & Mumbai',
    createdAt: '2026-08-10T09:30:00Z',
    updatedAt: '2026-09-28T14:15:00Z',
    tags: ['Cyber Crime', 'Money Laundering', 'UPI Fraud', 'Crypto Wallet'],
    entityCount: 14,
    evidenceCount: 18,
    relationshipCount: 22,
  },
  {
    id: 'case-102',
    caseNumber: 'CASE-2026-9043',
    title: 'Operation Viper Ring: Multi-State Narcotics Syndicate',
    description: 'Targeted intelligence probe into interstate supply chains, illegal communication channels, and illicit vehicle logistics across regional checkpoints.',
    status: 'OPEN',
    priority: 'HIGH',
    crimeType: 'Organized Narcotics Trafficking',
    assignedTo: 'usr-2',
    assignedUserName: 'Dr. Priya Sundaram',
    locationName: 'Noida & Hyderabad',
    createdAt: '2026-08-22T11:00:00Z',
    updatedAt: '2026-09-27T16:45:00Z',
    tags: ['Narcotics', 'Smuggling', 'CCTV Tracking', 'Encrypted Calls'],
    entityCount: 9,
    evidenceCount: 11,
    relationshipCount: 14,
  },
  {
    id: 'case-103',
    caseNumber: 'CASE-2026-7721',
    title: 'Operation Hawkeye: High-End Vehicle Theft Network',
    description: 'Racket modifying chassis numbers, fabricating forged registration documents, and transferring stolen luxury vehicles across international borders.',
    status: 'COLD_CASE',
    priority: 'MEDIUM',
    crimeType: 'Organized Vehicle Theft',
    assignedTo: 'usr-1',
    assignedUserName: 'Inspector Rajesh Varma',
    locationName: 'Chennai Port & NCR',
    createdAt: '2026-06-15T08:00:00Z',
    updatedAt: '2026-09-10T10:00:00Z',
    tags: ['Automobile Theft', 'Forgery', 'Customs Fraud'],
    entityCount: 6,
    evidenceCount: 8,
    relationshipCount: 9,
  },
];

export const MOCK_ENTITIES: Entity[] = [
  {
    id: 'ent-1',
    name: 'Ramesh Kumar',
    type: 'PERSON',
    attributes: {
      alias: 'Rajesh / Kingpin',
      dob: '1984-05-14',
      nationalId: 'PAN-ABCDE1234F',
      riskScore: 88,
      status: 'Prime Suspect',
    },
    confidence: 0.95,
    caseIds: ['case-101', 'case-102'],
    riskLevel: 'CRITICAL',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-11T10:00:00Z',
    notes: 'Identified as mastermind behind Apex Trading shell bank transfers.',
  },
  {
    id: 'ent-2',
    name: 'R. Kumar',
    type: 'PERSON',
    attributes: {
      alias: 'Ramesh K.',
      phone: '+91 98765 43210',
      riskScore: 75,
    },
    confidence: 0.82,
    caseIds: ['case-101'],
    riskLevel: 'HIGH',
    reviewStatus: 'UNVERIFIED',
    createdDate: '2026-08-15T14:20:00Z',
    notes: 'Possible duplicate of Ramesh Kumar captured from CDR logs.',
  },
  {
    id: 'ent-3',
    name: 'Vikram Singh',
    type: 'PERSON',
    attributes: {
      alias: 'Vicky',
      role: 'Mule Account Recruiter',
      location: 'Noida',
    },
    confidence: 0.91,
    caseIds: ['case-101'],
    riskLevel: 'HIGH',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-12T09:15:00Z',
  },
  {
    id: 'ent-4',
    name: 'Ananya Sharma',
    type: 'PERSON',
    attributes: {
      profession: 'Accountant',
      company: 'Apex Trading Pvt Ltd',
    },
    confidence: 0.88,
    caseIds: ['case-101'],
    riskLevel: 'MEDIUM',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-14T11:30:00Z',
  },
  {
    id: 'ent-5',
    name: '+91 98765 43210',
    type: 'PHONE',
    attributes: {
      carrier: 'Bharti Airtel',
      imei: '869402049102948',
      circle: 'Karnataka & Goa',
      status: 'Active Encrypted Node',
    },
    confidence: 0.98,
    caseIds: ['case-101'],
    riskLevel: 'CRITICAL',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-11T12:00:00Z',
  },
  {
    id: 'ent-6',
    name: '+91 91234 56789',
    type: 'PHONE',
    attributes: {
      carrier: 'Reliance Jio',
      imei: '358920194820193',
      circle: 'Delhi NCR',
    },
    confidence: 0.92,
    caseIds: ['case-101', 'case-102'],
    riskLevel: 'HIGH',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-13T15:45:00Z',
  },
  {
    id: 'ent-7',
    name: 'ramesh.kumar@apex-trading.in',
    type: 'EMAIL',
    attributes: {
      provider: 'ProtonMail / Custom Domain',
      createdIp: '185.220.101.5',
    },
    confidence: 0.94,
    caseIds: ['case-101'],
    riskLevel: 'HIGH',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-12T16:00:00Z',
  },
  {
    id: 'ent-8',
    name: 'KA-01-MJ-4091',
    type: 'VEHICLE',
    attributes: {
      makeModel: 'Black Toyota Fortuner 2024',
      chassisNumber: 'MBJ11294029104',
      ownerName: 'Apex Trading Pvt Ltd',
    },
    confidence: 0.96,
    caseIds: ['case-101', 'case-102'],
    riskLevel: 'HIGH',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-14T08:30:00Z',
  },
  {
    id: 'ent-9',
    name: 'HDFC-ACCT-908122',
    type: 'BANK_ACCOUNT',
    attributes: {
      bank: 'HDFC Bank, Koramangala Branch',
      accountHolder: 'Ramesh Kumar',
      balance: '₹ 1,42,50,000',
    },
    confidence: 0.99,
    caseIds: ['case-101'],
    riskLevel: 'CRITICAL',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-11T14:10:00Z',
  },
  {
    id: 'ent-10',
    name: 'ramesh.kumar@upi',
    type: 'UPI_ID',
    attributes: {
      linkedBank: 'HDFC Bank',
      status: 'Frozen by Cyber Cell',
    },
    confidence: 0.97,
    caseIds: ['case-101'],
    riskLevel: 'HIGH',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-12T10:00:00Z',
  },
  {
    id: 'ent-11',
    name: '0x71C765...89A2',
    type: 'CRYPTO_WALLET',
    attributes: {
      blockchain: 'Ethereum / USDT TRC-20',
      totalTransferred: '$ 450,000 USD',
    },
    confidence: 0.89,
    caseIds: ['case-101'],
    riskLevel: 'CRITICAL',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-16T18:00:00Z',
  },
  {
    id: 'ent-12',
    name: 'Apex Trading Pvt Ltd',
    type: 'ORGANIZATION',
    attributes: {
      registrationNo: 'CIN-U72900KA2024PTC192019',
      address: 'Suite 402, Embassy Tech Square, Bengaluru',
      type: 'Shell Enterprise',
    },
    confidence: 0.96,
    caseIds: ['case-101'],
    riskLevel: 'CRITICAL',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-11T09:00:00Z',
  },
  {
    id: 'ent-13',
    name: 'MG Road Cyber Cell Safehouse',
    type: 'LOCATION',
    attributes: {
      city: 'Bengaluru',
      state: 'Karnataka',
      coordinates: '12.9716, 77.5946',
    },
    confidence: 0.90,
    caseIds: ['case-101'],
    riskLevel: 'MEDIUM',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-12T12:00:00Z',
  },
  {
    id: 'ent-14',
    name: 'Sector 62 Tech Park',
    type: 'LOCATION',
    attributes: {
      city: 'Noida',
      state: 'Uttar Pradesh',
      coordinates: '28.6280, 77.3649',
    },
    confidence: 0.88,
    caseIds: ['case-101', 'case-102'],
    riskLevel: 'HIGH',
    reviewStatus: 'VERIFIED',
    createdDate: '2026-08-20T11:00:00Z',
  },
];

export const MOCK_RESOLUTION_CANDIDATES: EntityResolutionCandidate[] = [
  {
    id: 'res-1',
    primaryEntityId: 'ent-1',
    candidateEntityId: 'ent-2',
    primaryEntity: MOCK_ENTITIES[0],
    candidateEntity: MOCK_ENTITIES[1],
    similarityScore: 0.89,
    matchingAttributes: ['Name Similarity (92%)', 'Shared Phone (+91 98765 43210)', 'Geographic Co-location'],
    supportingEvidenceIds: ['ev-101', 'ev-104'],
    status: 'PENDING',
  },
  {
    id: 'res-2',
    primaryEntityId: 'ent-1',
    candidateEntityId: 'ent-3',
    primaryEntity: MOCK_ENTITIES[0],
    candidateEntity: MOCK_ENTITIES[2],
    similarityScore: 0.64,
    matchingAttributes: ['Shared Bank Transfer Logs', 'Co-located CCTV Frame'],
    supportingEvidenceIds: ['ev-102', 'ev-105'],
    status: 'DEFERRED',
    notes: 'Awaiting financial audit report for proof of identity overlap.',
  },
];

export const MOCK_RELATIONSHIPS: Relationship[] = [
  {
    id: 'rel-1',
    sourceEntityId: 'ent-1', // Ramesh Kumar
    targetEntityId: 'ent-5', // +91 98765 43210
    sourceEntityName: 'Ramesh Kumar',
    sourceEntityType: 'PERSON',
    targetEntityName: '+91 98765 43210',
    targetEntityType: 'PHONE',
    type: 'OWNED',
    confidenceScore: 0.98,
    evidenceIds: ['ev-101', 'ev-104'],
    caseId: 'case-101',
    timestamp: '2026-08-11T12:00:00Z',
    reviewStatus: 'VERIFIED',
  },
  {
    id: 'rel-2',
    sourceEntityId: 'ent-1', // Ramesh Kumar
    targetEntityId: 'ent-9', // HDFC-ACCT-908122
    sourceEntityName: 'Ramesh Kumar',
    sourceEntityType: 'PERSON',
    targetEntityName: 'HDFC-ACCT-908122',
    targetEntityType: 'BANK_ACCOUNT',
    type: 'OWNED',
    confidenceScore: 0.99,
    evidenceIds: ['ev-102'],
    caseId: 'case-101',
    timestamp: '2026-08-11T14:10:00Z',
    reviewStatus: 'VERIFIED',
  },
  {
    id: 'rel-3',
    sourceEntityId: 'ent-1', // Ramesh Kumar
    targetEntityId: 'ent-12', // Apex Trading Pvt Ltd
    sourceEntityName: 'Ramesh Kumar',
    sourceEntityType: 'PERSON',
    targetEntityName: 'Apex Trading Pvt Ltd',
    targetEntityType: 'ORGANIZATION',
    type: 'WORKED_WITH',
    confidenceScore: 0.95,
    evidenceIds: ['ev-103'],
    caseId: 'case-101',
    timestamp: '2026-08-11T09:00:00Z',
    reviewStatus: 'VERIFIED',
  },
  {
    id: 'rel-4',
    sourceEntityId: 'ent-5', // +91 98765 43210
    targetEntityId: 'ent-6', // +91 91234 56789
    sourceEntityName: '+91 98765 43210',
    sourceEntityType: 'PHONE',
    targetEntityName: '+91 91234 56789',
    targetEntityType: 'PHONE',
    type: 'CALLED',
    confidenceScore: 0.96,
    evidenceIds: ['ev-104'],
    caseId: 'case-101',
    timestamp: '2026-08-18T19:42:00Z',
    reviewStatus: 'VERIFIED',
    metadata: { durationSec: 420, callCount: 14 },
  },
  {
    id: 'rel-5',
    sourceEntityId: 'ent-3', // Vikram Singh
    targetEntityId: 'ent-6', // +91 91234 56789
    sourceEntityName: 'Vikram Singh',
    sourceEntityType: 'PERSON',
    targetEntityName: '+91 91234 56789',
    targetEntityType: 'PHONE',
    type: 'USED',
    confidenceScore: 0.91,
    evidenceIds: ['ev-104'],
    caseId: 'case-101',
    timestamp: '2026-08-13T15:45:00Z',
    reviewStatus: 'VERIFIED',
  },
  {
    id: 'rel-6',
    sourceEntityId: 'ent-9', // HDFC Bank Account
    targetEntityId: 'ent-11', // Crypto Wallet
    sourceEntityName: 'HDFC-ACCT-908122',
    sourceEntityType: 'BANK_ACCOUNT',
    targetEntityName: '0x71C765...89A2',
    targetEntityType: 'CRYPTO_WALLET',
    type: 'TRANSFERRED_TO',
    confidenceScore: 0.94,
    evidenceIds: ['ev-102', 'ev-106'],
    caseId: 'case-101',
    timestamp: '2026-08-16T18:00:00Z',
    reviewStatus: 'VERIFIED',
    metadata: { amount: '₹ 45,000,000 INR', currency: 'USDT' },
  },
  {
    id: 'rel-7',
    sourceEntityId: 'ent-1', // Ramesh Kumar
    targetEntityId: 'ent-8', // Vehicle KA-01-MJ-4091
    sourceEntityName: 'Ramesh Kumar',
    sourceEntityType: 'PERSON',
    targetEntityName: 'KA-01-MJ-4091',
    targetEntityType: 'VEHICLE',
    type: 'SEEN_WITH',
    confidenceScore: 0.88,
    evidenceIds: ['ev-105'],
    caseId: 'case-101',
    timestamp: '2026-08-20T21:15:00Z',
    reviewStatus: 'VERIFIED',
  },
  {
    id: 'rel-8',
    sourceEntityId: 'ent-8', // Vehicle KA-01-MJ-4091
    targetEntityId: 'ent-14', // Sector 62 Noida
    sourceEntityName: 'KA-01-MJ-4091',
    sourceEntityType: 'VEHICLE',
    targetEntityName: 'Sector 62 Tech Park',
    targetEntityType: 'LOCATION',
    type: 'LOCATED_AT',
    confidenceScore: 0.93,
    evidenceIds: ['ev-105'],
    caseId: 'case-101',
    timestamp: '2026-08-20T21:15:00Z',
    reviewStatus: 'VERIFIED',
  },
  {
    id: 'rel-9',
    sourceEntityId: 'ent-4', // Ananya Sharma
    targetEntityId: 'ent-12', // Apex Trading
    sourceEntityName: 'Ananya Sharma',
    sourceEntityType: 'PERSON',
    targetEntityName: 'Apex Trading Pvt Ltd',
    targetEntityType: 'ORGANIZATION',
    type: 'WORKED_WITH',
    confidenceScore: 0.89,
    evidenceIds: ['ev-103'],
    caseId: 'case-101',
    timestamp: '2026-08-14T11:30:00Z',
    reviewStatus: 'VERIFIED',
  },
];

export const MOCK_EVIDENCE: Evidence[] = [
  {
    id: 'ev-101',
    evidenceNumber: 'EVD-2026-0091',
    caseId: 'case-101',
    title: 'Seized Encrypted Smartphone Digital Extract',
    type: 'CALL_RECORD',
    source: 'Cyber Forensics Lab & Telecom Gateway Extract',
    sourceReference: 'CFL-REPORT-8849-B',
    timestamp: '2026-08-11T12:00:00Z',
    uploadedBy: 'Inspector Rajesh Varma',
    hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    processingStatus: 'PROCESSED',
    linkedEntityIds: ['ent-1', 'ent-5', 'ent-7'],
    metadata: {
      fileType: 'JSON/CDR',
      totalRecords: 1420,
      extractorSoftware: 'Cellebrite UFED v7.6',
    },
    description: 'Extracted call detail records (CDR) and encrypted WhatsApp metadata showing communications with overseas proxy numbers.',
  },
  {
    id: 'ev-102',
    evidenceNumber: 'EVD-2026-0092',
    caseId: 'case-101',
    title: 'Bank Ledger & Wire Transfer Documentation',
    type: 'FINANCIAL_TRANSACTION',
    source: 'Financial Intelligence Unit (FIU-IND) Query',
    sourceReference: 'FIU-STR-2026-904',
    timestamp: '2026-08-11T14:10:00Z',
    uploadedBy: 'Dr. Priya Sundaram',
    hash: 'a591a6d40bf420404a011733cfb7b190d62c65bf0bcda32b57b277d9ad9f146e',
    processingStatus: 'PROCESSED',
    linkedEntityIds: ['ent-1', 'ent-9', 'ent-10', 'ent-11'],
    metadata: {
      totalVolume: '₹ 4.5 Crore',
      bankCount: 3,
      flaggedTransactions: 14,
    },
    description: 'Suspicious Transaction Reports (STR) detailing layered transfers from HDFC account to UPI nodes and crypto off-ramps.',
  },
  {
    id: 'ev-103',
    evidenceNumber: 'EVD-2026-0093',
    caseId: 'case-101',
    title: 'Company Registration & Shell Incorporation Deed',
    type: 'DOCUMENT',
    source: 'Ministry of Corporate Affairs (MCA) Registry',
    sourceReference: 'MCA-CIN-192019',
    timestamp: '2026-08-11T09:00:00Z',
    uploadedBy: 'Dr. Priya Sundaram',
    hash: '7d8ad5da4a3b49708701376541012351234123141235234512345',
    processingStatus: 'PROCESSED',
    linkedEntityIds: ['ent-1', 'ent-4', 'ent-12'],
    metadata: {
      pageCount: 24,
      signatories: 'Ramesh Kumar, Ananya Sharma',
    },
    description: 'Official corporate filing showing Apex Trading Pvt Ltd incorporated with virtual office address and zero legitimate operational turnover.',
  },
  {
    id: 'ev-104',
    evidenceNumber: 'EVD-2026-0094',
    caseId: 'case-101',
    title: 'Cell Site Location Dump & Tower Ping Analysis',
    type: 'LOCATION_RECORD',
    source: 'Telecom Service Provider Signal Analysis',
    sourceReference: 'TSP-TOWER-BGLR-092',
    timestamp: '2026-08-18T19:42:00Z',
    uploadedBy: 'Inspector Rajesh Varma',
    hash: '1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef',
    processingStatus: 'PROCESSED',
    linkedEntityIds: ['ent-2', 'ent-5', 'ent-6', 'ent-13'],
    metadata: {
      towerLocation: 'Koramangala 4th Block',
      overlapDuration: '45 mins',
    },
    description: 'Tower dumps indicating simultaneous presence of target mobile numbers near safehouse premises.',
  },
  {
    id: 'ev-105',
    evidenceNumber: 'EVD-2026-0095',
    caseId: 'case-101',
    title: 'Highway ANPR Camera Footage & License Plate Match',
    type: 'CCTV',
    source: 'State Highway ANPR Surveillance Network',
    sourceReference: 'ANPR-CAM-NOIDA-62',
    timestamp: '2026-08-20T21:15:00Z',
    uploadedBy: 'Inspector Rajesh Varma',
    hash: 'cba987654321fedcba987654321fedcba987654321fedcba987654321fedcba',
    processingStatus: 'PROCESSED',
    linkedEntityIds: ['ent-1', 'ent-8', 'ent-14'],
    metadata: {
      cameraID: 'ANPR-62-NORTH',
      confidence: '98.4%',
      resolution: '4K Ultra HD',
    },
    description: 'Automatic Number Plate Recognition log confirming black Toyota Fortuner KA-01-MJ-4091 passing toll gate with primary suspect.',
  },
  {
    id: 'ev-106',
    evidenceNumber: 'EVD-2026-0096',
    caseId: 'case-101',
    title: 'Blockchain Transaction Trace & Crypto Analytics Report',
    type: 'FINANCIAL_TRANSACTION',
    source: 'Chainalysis / Elliptic Intelligence Export',
    sourceReference: 'CHAIN-TRACE-USDT-991',
    timestamp: '2026-08-16T18:00:00Z',
    uploadedBy: 'Dr. Priya Sundaram',
    hash: '887766554433221100aabbccddeeff00112233445566778899aabbccddeeff00',
    processingStatus: 'PROCESSED',
    linkedEntityIds: ['ent-9', 'ent-11'],
    metadata: {
      currency: 'USDT',
      hops: 4,
      destExchanges: 'Binance, OKX',
    },
    description: 'On-chain forensic report showing 450,000 USDT routed through mixer smart contracts into non-custodial wallet.',
  },
];

export const MOCK_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: 'evt-1',
    caseId: 'case-101',
    entityId: 'ent-12',
    entityName: 'Apex Trading Pvt Ltd',
    entityType: 'ORGANIZATION',
    eventType: 'EVIDENCE_UPLOAD',
    timestamp: '2026-08-11T09:00:00Z',
    description: 'Shell corporation deed registered at Registrar of Companies (ROC).',
    evidenceId: 'ev-103',
    confidence: 0.99,
  },
  {
    id: 'evt-2',
    caseId: 'case-101',
    entityId: 'ent-1',
    entityName: 'Ramesh Kumar',
    entityType: 'PERSON',
    eventType: 'INVESTIGATOR_ACTION',
    timestamp: '2026-08-11T10:00:00Z',
    description: 'Case registered and suspect profile created in CRIMENEXUS database.',
    confidence: 1.0,
  },
  {
    id: 'evt-3',
    caseId: 'case-101',
    entityId: 'ent-9',
    entityName: 'HDFC-ACCT-908122',
    entityType: 'BANK_ACCOUNT',
    eventType: 'BANK_TRANSFER',
    timestamp: '2026-08-11T14:10:00Z',
    description: 'First suspicious high-value wire transfer of ₹ 50,000,000 executed.',
    location: 'HDFC Koramangala Branch',
    evidenceId: 'ev-102',
    confidence: 0.99,
  },
  {
    id: 'evt-4',
    caseId: 'case-101',
    entityId: 'ent-5',
    entityName: '+91 98765 43210',
    entityType: 'PHONE',
    eventType: 'CALL',
    timestamp: '2026-08-18T19:42:00Z',
    description: 'Encrypted call duration 7 minutes logged between suspect and unknown proxy phone (+91 91234 56789).',
    location: 'Koramangala Tower Ping',
    evidenceId: 'ev-104',
    confidence: 0.96,
  },
  {
    id: 'evt-5',
    caseId: 'case-101',
    entityId: 'ent-8',
    entityName: 'KA-01-MJ-4091',
    entityType: 'VEHICLE',
    eventType: 'VEHICLE_DETECTION',
    timestamp: '2026-08-20T21:15:00Z',
    description: 'Toyota Fortuner recorded passing Sector 62 Expressway camera checkpoint.',
    location: 'Sector 62 Noida',
    evidenceId: 'ev-105',
    confidence: 0.98,
  },
  {
    id: 'evt-6',
    caseId: 'case-101',
    entityId: 'ent-11',
    entityName: '0x71C765...89A2',
    entityType: 'CRYPTO_WALLET',
    eventType: 'BANK_TRANSFER',
    timestamp: '2026-08-25T11:00:00Z',
    description: 'Crypto off-ramp transfer of 450,000 USDT routed to offshore exchange.',
    evidenceId: 'ev-106',
    confidence: 0.94,
  },
];

export const MOCK_MAP_LOCATIONS: MapLocation[] = [
  {
    id: 'loc-1',
    title: 'MG Road Cyber Cell Safehouse',
    entityType: 'LOCATION',
    locationType: 'CRIME_SCENE',
    latitude: 12.9716,
    longitude: 77.5946,
    address: 'MG Road, Sector 3, Bengaluru, Karnataka',
    timestamp: '2026-08-12T12:00:00Z',
    entityId: 'ent-13',
    entityName: 'MG Road Cyber Cell Safehouse',
    caseId: 'case-101',
    metadata: { status: 'Under Surveillance', policeZone: 'Bengaluru Central' },
  },
  {
    id: 'loc-2',
    title: 'Sector 62 ANPR Checkpoint',
    entityType: 'VEHICLE',
    locationType: 'VEHICLE_DETECTION',
    latitude: 28.628,
    longitude: 77.3649,
    address: 'Sector 62 Expressway ANPR Toll, Noida, UP',
    timestamp: '2026-08-20T21:15:00Z',
    entityId: 'ent-8',
    entityName: 'KA-01-MJ-4091',
    caseId: 'case-101',
    metadata: { vehicle: 'Toyota Fortuner', speed: '72 km/h' },
  },
  {
    id: 'loc-3',
    title: 'Koramangala Cell Tower Ping #409',
    entityType: 'PHONE',
    locationType: 'PHONE_CELL_TOWER',
    latitude: 12.9352,
    longitude: 77.6245,
    address: 'Koramangala 4th Block, Bengaluru',
    timestamp: '2026-08-18T19:42:00Z',
    entityId: 'ent-5',
    entityName: '+91 98765 43210',
    caseId: 'case-101',
    metadata: { callType: 'VoIP / Data', provider: 'Airtel Tower BGLR-09' },
  },
  {
    id: 'loc-4',
    title: 'Customs Terminal 3 Surveillance',
    entityType: 'LOCATION',
    locationType: 'CCTV_SIGHTING',
    latitude: 18.9438,
    longitude: 72.836,
    address: 'Navi Mumbai Port Customs Zone, Mumbai',
    timestamp: '2026-08-22T08:30:00Z',
    entityId: 'ent-1',
    entityName: 'Ramesh Kumar',
    caseId: 'case-101',
    metadata: { camId: 'PORT-CCTV-12', matchScore: '94%' },
  },
];

export const MOCK_AI_FINDINGS: AIFinding[] = [
  {
    id: 'ai-1',
    caseId: 'case-101',
    title: 'Money Laundering Hub & Crypto Off-Ramp Discovered',
    finding: 'Multi-layer financial analysis indicates HDFC-ACCT-908122 acts as a central collection hub, disbursing funds directly to crypto wallet 0x71C765...89A2 within 45 minutes of receipt.',
    confidence: 0.94,
    supportingEvidenceIds: ['ev-102', 'ev-106'],
    relatedEntityIds: ['ent-1', 'ent-9', 'ent-11'],
    timestamp: '2026-09-28T10:30:00Z',
    category: 'SUSPICIOUS_TRANSACTION',
    riskLevel: 'CRITICAL',
    queryText: 'Explain the connections found in this case',
  },
  {
    id: 'ai-2',
    caseId: 'case-101',
    title: 'Entity Resolution High-Confidence Match',
    finding: 'Candidate duplicate entity "R. Kumar" (+91 98765 43210) matches primary suspect "Ramesh Kumar" with 89% similarity across shared phone numbers, cell site towers, and associated shell company deeds.',
    confidence: 0.89,
    supportingEvidenceIds: ['ev-101', 'ev-103', 'ev-104'],
    relatedEntityIds: ['ent-1', 'ent-2', 'ent-5'],
    timestamp: '2026-09-27T14:15:00Z',
    category: 'PATTERN_MATCH',
    riskLevel: 'HIGH',
    queryText: 'Show candidate duplicate entities for Ramesh Kumar',
  },
  {
    id: 'ai-3',
    caseId: 'case-101',
    title: 'Co-location of Suspect Vehicle & Key Operatives',
    finding: 'Cell site logs and ANPR footage place suspect vehicle KA-01-MJ-4091 and mobile node +91 91234 56789 at Sector 62 Noida Tech Park within a 15-minute window on August 20.',
    confidence: 0.92,
    supportingEvidenceIds: ['ev-104', 'ev-105'],
    relatedEntityIds: ['ent-6', 'ent-8', 'ent-14'],
    timestamp: '2026-09-26T16:00:00Z',
    category: 'CO_LOCATION',
    riskLevel: 'HIGH',
    queryText: 'Summarize the investigation timeline',
  },
];

export const MOCK_REPORTS: IntelligenceReport[] = [
  {
    id: 'rep-1',
    title: 'Operation Shadow Vault - Master Comprehensive Intelligence Report',
    type: 'CASE_SUMMARY',
    caseId: 'case-101',
    caseTitle: 'Operation Shadow Vault: Cyber Financial Syndicate',
    generatedBy: 'Dr. Priya Sundaram (Senior Analyst)',
    generatedAt: '2026-09-28T15:00:00Z',
    summaryStats: {
      totalEntities: 14,
      totalEvidence: 18,
      totalRelationships: 22,
      aiFindingsCount: 3,
    },
    content: {
      executiveSummary: 'This intelligence report outlines the organizational structure, financial channels, and technical infrastructure of the cyber crime syndicate operating under Apex Trading Pvt Ltd.',
      keyFindings: [
        'Ramesh Kumar identified as primary controller of HDFC bank account and crypto wallets.',
        'Total illicit transaction volume tracked exceeds ₹ 4.5 Crore INR.',
        'Mule account recruitment spearheaded by Vikram Singh in NCR region.',
      ],
      riskAssessment: 'HIGH CRITICAL: Immediate risk of capital flight into non-custodial crypto mixers. Freezing orders issued for identified accounts.',
      recommendedActions: [
        'Issue formal seizure notice for HDFC-ACCT-908122.',
        'Request INTERPOL Interpol Purple Notice for crypto exchange off-ramps.',
        'Execute physical search warrant at Sector 62 Noida tech park premises.',
      ],
    },
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-101',
    timestamp: '2026-09-29T14:30:12Z',
    userId: 'usr-1',
    userName: 'Inspector Rajesh Varma',
    userRole: 'INVESTIGATOR',
    action: 'LOGIN',
    target: 'System Console',
    ipAddress: '10.240.12.89',
  },
  {
    id: 'log-102',
    timestamp: '2026-09-29T14:35:40Z',
    userId: 'usr-1',
    userName: 'Inspector Rajesh Varma',
    userRole: 'INVESTIGATOR',
    action: 'GRAPH_INVESTIGATED',
    target: 'Case CASE-2026-8812 Cytoscape Graph',
    caseId: 'case-101',
    metadata: { nodeCount: 14, edgeCount: 22, selectedNode: 'Ramesh Kumar' },
    ipAddress: '10.240.12.89',
  },
  {
    id: 'log-103',
    timestamp: '2026-09-29T14:40:05Z',
    userId: 'usr-2',
    userName: 'Dr. Priya Sundaram',
    userRole: 'ANALYST',
    action: 'AI_QUERY',
    target: 'AI Investigation Assistant',
    caseId: 'case-101',
    metadata: { query: 'Explain the connections found in this case' },
    ipAddress: '10.240.14.12',
  },
  {
    id: 'log-104',
    timestamp: '2026-09-29T14:45:19Z',
    userId: 'usr-2',
    userName: 'Dr. Priya Sundaram',
    userRole: 'ANALYST',
    action: 'EVIDENCE_VIEWED',
    target: 'Evidence EVD-2026-0092 (Bank Ledger)',
    caseId: 'case-101',
    metadata: { evidenceType: 'FINANCIAL_TRANSACTION' },
    ipAddress: '10.240.14.12',
  },
  {
    id: 'log-105',
    timestamp: '2026-09-29T15:00:00Z',
    userId: 'usr-3',
    userName: 'Superintendent K. S. Rao',
    userRole: 'SUPERVISOR',
    action: 'REPORT_GENERATED',
    target: 'Master Comprehensive Intelligence Report',
    caseId: 'case-101',
    metadata: { reportType: 'CASE_SUMMARY' },
    ipAddress: '10.240.10.01',
  },
];
